# Generated by Django 5.0.6 on 2024-12-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_dish_created_at_dish_modified_at_alter_dish_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='employeeaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdminAccount',
        ),
        migrations.DeleteModel(
            name='EmployeeAccount',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
