# Generated by Django 5.0.6 on 2024-12-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with this email address already exists.'}, help_text='Please enter a valid email address.', max_length=254, unique=True),
        ),
    ]
