# Generated by Django 5.0.6 on 2025-01-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='max_usage',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
