# Generated by Django 5.0.6 on 2025-01-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_discountcode_max_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='used_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
