# Generated by Django 5.0.6 on 2025-01-12 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_discountcode_used_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountcode',
            old_name='max_usage',
            new_name='max_usage_per_user',
        ),
        migrations.CreateModel(
            name='UserDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('discount_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.discountcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
