# Generated by Django 5.0.6 on 2025-01-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pending_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
