from django.urls import path, include
from .views import (
    DishAPIView,
    CategoryListAPIView,
    CustomAuthTokenView,
    EmployeeAPIView,
    CustomerRegistrationAPIView,
    CustomerDishListView,
    CompleteOrderAPIView,
    EmployeePendingOrdersView,
    UpdateOrderStatusView,
    CompletedOrderListView,
    TopOrderedDishesView,
    RateAPIView,
    AddressListCreateView,
    DiscountCodeListCreateView,
    ApplyDiscountCodeView,
    CancelOrderAPIView,
    PendingOrdersAPIView,
    CompletedOrdersAPIView,
    TopOrderedDishesManagerView,
    OrdersInDateRangeView
)
urlpatterns = [
    path('dishes/', DishAPIView.as_view(), name='dish-list-create'),
    path('dishes/<int:pk>/', DishAPIView.as_view(), name='dish-detail'),
    path('categories/', CategoryListAPIView.as_view(), name='category-list'),
    path('token-auth/', CustomAuthTokenView.as_view(), name='api_token_auth'),
    path('employee/', EmployeeAPIView.as_view(), name='employee') ,
    path('employee/<int:pk>/', EmployeeAPIView.as_view(), name='employee-detail'),
    path('customer-registration/' , CustomerRegistrationAPIView.as_view(),name='customer-signup'),
    path('customer-dishes/', CustomerDishListView.as_view(), name='customer-dishes-list'),
    path('complete-order/', CompleteOrderAPIView.as_view(), name='complete-order'),
    path('orders/', EmployeePendingOrdersView.as_view(), name='employee-order-list'),
    path('orders/<int:order_id>/update-status/', UpdateOrderStatusView.as_view(), name='update-order-status'),
    path('completed-orders/', CompletedOrderListView.as_view(), name='complete-order'),
    path('top-ordered-dishes/', TopOrderedDishesView.as_view(), name='top-ordered-dishes'),
    path('rates/', RateAPIView.as_view(), name='reviews'),
    path('rates/<int:dish_id>', RateAPIView.as_view(), name='submit-rate'),
    path('addresses/', AddressListCreateView.as_view(), name='address-list-create'),  # Create and list addresses
    path('discount-codes/', DiscountCodeListCreateView.as_view(), name='discount_code_list_create'),
    path('apply-discount/', ApplyDiscountCodeView.as_view(), name='apply-discount'),
    path('apply-discount/', ApplyDiscountCodeView.as_view(), name='apply-discount'),
    path('orders/pending/', PendingOrdersAPIView.as_view(), name='pending-orders'),
    path('orders/cancel/', CancelOrderAPIView.as_view(), name='cancel-order'),
    path('orders/completed/', CompletedOrdersAPIView.as_view(), name='completed-orders'),
    path('top-solds/', TopOrderedDishesManagerView.as_view(), name='top-ordered-dishes'),
    path('orders-in-date-range/', OrdersInDateRangeView.as_view(), name='orders_in_date_range'),
]